# Generated by Django 3.2.9 on 2021-12-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_newquiz_quesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quizScore',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
